Title: Caravana Cloud - Agenda tu solicitud de Workshop
Author: Fernando Honig / Julio Faerman
Image: https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png
Theme: 282828
Questions:
    Question1:
        Type: ShortText
        Label: "Nombre y Apellido:"
    Question2:
        Type: ShortText
        Label: "Email:"
    Question3:
        Type: ShortText
        Label: "Telefono:"
    Question4:
        Type: ShortText
        Label: "Empresa:"
    Question5:
        Type: Radio
        Label: Eres AWS Partner?
        Values:
            Value1: Si
            Value2: No
    Question6:
        Type: Radio
        Label: Te gustaria que hagamos un Workshop en tu ciudad?
        Values:
            Value1: Si
            Value2: No
    Question7:
        Type: Text
        Label: En que Ciudad/Pais vives?
    Question8:
        Type: Radio
        Label: Puedes ayudarnos a conseguir un lugar para 20/30 personas?
        Values:
            Value1: Si
            Value2: No
    Question8:
        Type: Radio
        Label: Que tema te gustaria que se trate principalmente en el Workshop?
        Values:
            Value1: Serverless
            Value2: Machine Learning
            Value3: Seguridad en la Nube
            Value4: Control de Costos
            Value5: Migraciones y Mejores Practicas
